plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aljwaal.used'
    compileSdk 35

    defaultConfig {
        applicationId "com.aljwaal.used"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "1.0.2-history"
    }

    buildTypes {
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
